### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by capolpo** [Beinsezii/NieR-Cursors#4]
Hi, i don't really understand all this build.sh/python stuff, what "tools" do i need to properly run the build.sh? i have python 3 installed, but when i click build and install the .inf, it shows that the files are corrupted/missing. It also shows this when i run build.sh

![image](https://github.com/user-attachments/assets/ea845668-9a3b-413e-bd61-def9f781600e)

Edit : Forgot to mention, but im on windows

Edit : I got ubuntu, installed the required tools, but now it says this :
![image](https://github.com/user-attachments/assets/b60d749a-1692-43b3-b402-87040bee6c63)

**Comment by Beinsezii** [comment]
Why not use the [pre-made windows package?](https://github.com/Beinsezii/NieR-Cursors/releases/tag/2020-08-25)

**Comment by capolpo** [comment]
> Why not use the [pre-made windows package?](https://github.com/Beinsezii/NieR-Cursors/releases/tag/2020-08-25)

I did, but the loading cursor isnt animated. Did i miss a step or something?


Edit : Ah wait i just realized windows is indeed missing animations, sorry about that

**Comment by Beinsezii** [comment]
> The loading cursor isnt animated

When I made this project I must have looked for a few hours trying to find a program to batch-write the windows animated cursor files. I could not get the Capitaine script working and there wasn't many resources going over the modified RIFF format they're packed as.

If you know a way to write Windows ANI files soundly with correct hotspots and animation times, let me know.

**Comment by capolpo** [comment]
> > The loading cursor isnt animated
> 
> When I made this project I must have looked for a few hours trying to find a program to batch-write the windows animated cursor files. I could not get the Capitaine script working and there wasn't many resources going over the modified RIFF format they're packed as.
> 
> If you know a way to write Windows ANI files soundly with correct hotspots and animation times, let me know.

i managed to animate the busy cursor, but the working in background requires me to manually create each frame, sadly i lack the knowledge to do that.

**Comment by Beinsezii** [comment]
One of the recent GIMP versions has an 
ani file saver but afaik it's not usable via the GObject API so the only way to do so is to manually import all 60 frames and set the hotspots yourself which I'm not willing to do.

It's been a few years so I'll have to look over the Internet again for some tools I can use (or even a RIFF+ANI spec sheet?) but right now the project doesn't even render properly on Blender 4.2 anymore so that needs to get fixed too...

**Comment by capolpo** [comment]
I managed to animate the loading icons, I can send if you want. For the "unavailable" cursor, I'm afraid I can't because I have no idea how to replicate the animation or extract the frames from the preview .webp
